### ISSUE TITLE
Modify the create/edit issue screen to only show open epics in 'epic link' field

### ISSUE THREAD

**Issue by brack** [johnhof/JiraJockey#21]
As we are transitioning to create more and more epics, I noticed that Jira shows closed epics in the 'suggestions' for the 'epic link' field. It'd be super convenient to only show open epics.

After talking with Shane, he said it may be possible to modify this behavior using JiraJockey. The solution we discussed is that when the create/edit screen is displayed, JiraJockey does a request using the project selected by the 'project' field and fills the 'suggestions' list with only open epics (not sure if we'd need to limit the amount it returns)

I may be able to do this myself, but I will need some guidance. This issue is mostly to have a discussion around the suggestion.

Thanks!

brack

**Comment by johnhof** [comment]
@brack Is this still needed? I know a lot has changed since this issue was submitted?

**Comment by brack** [comment]
dayyyyuuuum i totally forgot about this. i've found some workarounds for this, which is to just close out the epics from the side panel.

that said, it would be amazing if the epics on the side would respond to quick filters...

but yeah, ultimately it's not that important

**Comment by johnhof** [comment]
Haha, sorry man. I remember talking about this, but I kind of let JJ go on autopilot once things started getting busy. I'll reopen if I find the time

**Comment by brack** [comment]
Cool man, all good. This feature was a bit more important at the time since we were just getting into new processes with JIRA agile, epics, etc.

Thanks for replying though, and if you do ever feel like adding or having the time let me know. I had meant to add this, just kept getting pushed back til i forgot
