### ISSUE TITLE
On install, seeing an error

### ISSUE THREAD

**Issue by kscherr** [johnhof/JiraJockey#36]
![screen shot 2014-12-19 at 5 01 16 pm](https://cloud.githubusercontent.com/assets/2460115/5511832/c826c010-87a0-11e4-93f0-868ea423ad92.png)
![screen shot 2014-12-19 at 5 01 30 pm](https://cloud.githubusercontent.com/assets/2460115/5511834/c82a4f3c-87a0-11e4-8501-f7794c3f6289.png)

**Comment by johnhof** [comment]
https://github.com/johnhof/JiraJockey/pull/39 Sorry about the turn around time :+1:
